scss_files: 'app/assets/stylesheets/**/*.css.scss'

exclude: 'node_modules/**'

linters:
  BorderZero:
    enabled: false

  Indentation:
    enabled: true
    severity: warning
    allow_non_nested_indentation: false
    character: 'tab' # or 'space'
    width: 1

  ColorVariable:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero # or 'include_zero'

  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
  
  PropertySpelling:
    enabled: false
    extra_properties: []
    disabled_properties: []
  
  HexLength:
    enabled: true
    style: long # or 'long'